#!/bin/sh
# Source tutorial run functions
iter=10
time=1

for ((i=1; i<=$iter; i++))
do
    touch $i.numiter
    pimpleFoam
    cp -r postProcessing/getValue/$time/down_foam/* deformation/
    cd deformation/
    ./AllrunDeform
    cd ../
    let "rem = $i % 10"
    if [ "$rem" = "0" ]
    then
       mv postProcessing postProcessing_i$i
    else
       rm -rf postProcessing/
    fi
#    mv postProcessing postProcessing_i$i
    rm -rf $time/
    rm -rf $i.numiter
done


